## Demonstração - Pytorch

### Tensors

In [2]:
import torch
import numpy as np

#Inicialização diretamente com dados - tipo inferido automaticamente
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

#Inicialização de um NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [3]:
#Cria tensor com shape específico e com valores 1.
#Shape (2, 3)
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
#Cria tensor com shape específico e com valores 0.
#Shape (3, 5)
zeros_tensor = torch.zeros(3,5)
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
# Cria tensor com shape específico e com valores aleaórios.

#Shape (10, 3)
x = torch.randn(10, 3)
print(x)

#Shape(10, 2)
y = torch.randn(10, 2)
print(y)


tensor([[ 0.6514,  0.5490, -1.1878],
        [-0.0483,  0.0965, -1.1458],
        [-2.0414,  0.0866,  1.2496],
        [-0.2292, -0.2232, -0.3304],
        [ 0.4538, -1.4553, -0.8975],
        [ 0.0118,  0.9182, -0.1548],
        [ 1.3575,  0.1637,  2.6603],
        [-0.5165, -1.5769, -0.6754],
        [ 0.0937,  0.1895, -0.4054],
        [ 0.9114, -0.8429, -0.4630]])
tensor([[-0.5143, -1.5079],
        [-0.1336, -1.3088],
        [ 0.3561,  0.3396],
        [-0.8006,  0.4334],
        [-0.2064, -1.0392],
        [ 0.6783,  0.1201],
        [-0.3587, -0.4145],
        [ 1.5335, -0.5212],
        [ 0.0656,  0.8821],
        [ 0.5137,  1.9258]])


In [6]:
#Atributos de um tensor

print(f"Shape do tensor: {x.shape}")
print(f"Datatype do tensor: {x.dtype}")
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Shape do tensor: torch.Size([10, 3])
Datatype do tensor: torch.float32
Dispositivo onde o tensor está armazenado: cpu


In [12]:
# Movendo o tensor para a GPU se disponível 
if torch.cuda.is_available():
    x = x.to('cuda')

print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Dispositivo onde o tensor está armazenado: cpu


### Manipulação de tensor 

As operações são similares a um Np-array


In [13]:
print('Primeira linha: ', x[0])
print('Primeira coluna: ', x[:, 0])
print('Ultima coluna:', x[:, -1])

print(x)

Primeira linha:  tensor([ 0.6514,  0.5490, -1.1878])
Primeira coluna:  tensor([ 0.6514, -0.0483, -2.0414, -0.2292,  0.4538,  0.0118,  1.3575, -0.5165,
         0.0937,  0.9114])
Ultima coluna: tensor([-1.1878, -1.1458,  1.2496, -0.3304, -0.8975, -0.1548,  2.6603, -0.6754,
        -0.4054, -0.4630])
tensor([[ 0.6514,  0.5490, -1.1878],
        [-0.0483,  0.0965, -1.1458],
        [-2.0414,  0.0866,  1.2496],
        [-0.2292, -0.2232, -0.3304],
        [ 0.4538, -1.4553, -0.8975],
        [ 0.0118,  0.9182, -0.1548],
        [ 1.3575,  0.1637,  2.6603],
        [-0.5165, -1.5769, -0.6754],
        [ 0.0937,  0.1895, -0.4054],
        [ 0.9114, -0.8429, -0.4630]])


## Criando modelos

Para definir uma rede neural em PyTorch, criamos uma classe que herda de nn.Module. Definimos as camadas da rede na função __init__ e especificamos como os dados passarão pela rede na função forward. <br>

Para acelerar as operações na rede neural, nós a movemos para a GPU, se disponível.

In [17]:
from torch import nn

# Construi uma camada fully connected
#torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
linear = nn.Linear(3, 2)

print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.2062,  0.4510, -0.2876],
        [-0.5043, -0.3405,  0.3996]], requires_grad=True)
b:  Parameter containing:
tensor([0.3599, 0.2842], requires_grad=True)


In [18]:
# Pega a GPU ou CPU para treinamento.
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Usando {}".format(device))

Usando cpu


In [20]:
linear = linear.to(device)
print(x)
#Operação - Forward.
pred = linear(x.to(device))

tensor([[ 0.6514,  0.5490, -1.1878],
        [-0.0483,  0.0965, -1.1458],
        [-2.0414,  0.0866,  1.2496],
        [-0.2292, -0.2232, -0.3304],
        [ 0.4538, -1.4553, -0.8975],
        [ 0.0118,  0.9182, -0.1548],
        [ 1.3575,  0.1637,  2.6603],
        [-0.5165, -1.5769, -0.6754],
        [ 0.0937,  0.1895, -0.4054],
        [ 0.9114, -0.8429, -0.4630]])


In [11]:
# Constroi a função de perda e otimização 
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(linear.parameters(), lr=0.01)


In [13]:
#Manda o y para a gpu
y = y.to(device)

# Computa a perda.
loss = criterion(pred, y)
print('Perda: ', loss.item())

# Procedimento de Backward.
loss.backward()

# 1-passo do 'gradient descent'.
optimizer.step()

# Imprime a perda depois de 1 passo do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 1 passo de otimização : ', loss.item())

#Mais um passo
loss.backward()
optimizer.step()

# Imprime a perda depois de 2 passos do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 2 passos de otimização : ', loss.item())

Perda:  0.8549615740776062
Perda depois de 1 passo de otimização :  0.8331798911094666
Perda depois de 2 passos de otimização :  0.811942994594574


### Um exemplo um pouco mais completo

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split

dfPropaganda = pd.read_csv('Advertising.csv')


y= dfPropaganda['Sales']
X = dfPropaganda.iloc[:,[1,2,3]]

y_tensor = torch.tensor(y)
X_tensor = torch.tensor(X.to_numpy())
print(y_tensor.shape)
print(X_tensor.shape)

X_treino, X_teste, y_treino, y_teste = train_test_split(X_tensor, y_tensor, test_size = 0.10, random_state=5)

print(X_treino.shape)
print(y_treino.shape)

X_treino = X_treino.float().to(device)
y_treino = y_treino.float().to(device)

X_teste = X_teste.float().to(device)
y_teste = y_teste.float().to(device)

torch.Size([200])
torch.Size([200, 3])
torch.Size([180, 3])
torch.Size([180])


### Implementa uma classe com o modelo

Para definir uma rede neural em PyTorch, criamos uma classe que herda de nn.Module. Definimos as camadas da rede na função __init__ e especificamos como os dados passarão pela rede na função forward. <br>


In [60]:
class Feedforward(torch.nn.Module):
    
        def __init__(self, input_size, hidden_size):
            super(Feedforward, self).__init__()
            
            self.input_size = input_size
            self.hidden_size  = hidden_size
            self.fc1 = torch.nn.Linear(self.input_size, self.hidden_size)
            self.fc2 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.fc3 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.fc4 = torch.nn.Linear(self.hidden_size, 1)
            
            self.relu = torch.nn.ReLU()
            
            
        def forward(self, x):
            output = self.fc1(x)
            output = self.relu(output)
            
            output = self.fc2(output)
            output = self.relu(output)
            
            output = self.fc3(output)
            output = self.relu(output)
            
            output = self.fc4(output)

            return output

### Modelo e critério de otimização
Para acelerar as operações na rede neural, nós a movemos para a GPU, se disponível.

In [66]:
#input = 3 (número de features), e hidden size = 10 (número de neurôneos na camada escondida)
model = Feedforward(3, 10).to(device)
print(model)
criterion = torch.nn.MSELoss()

optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

Feedforward(
  (fc1): Linear(in_features=3, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=10, bias=True)
  (fc4): Linear(in_features=10, out_features=1, bias=True)
  (relu): ReLU()
)


### Treino e teste do modelo

In [67]:
model.eval()
y_pred = model(X_teste)
antes_treino = criterion(y_pred, y_teste) 
print('Teste - perda antes do treinamento' , antes_treino.item())

model.train()
epoch = 100

for epoch in range(epoch):
    optimizer.zero_grad()
    
    # Passe Forward
    y_pred = model(X_treino)
    
    # Computa a perda
    loss = criterion(y_pred, y_treino)
    
    print('Epoch {}: perda treino: {}'.format(epoch, loss.item()))
    
    # Passe de Backward
    loss.backward()
    optimizer.step()

    
model.eval()
y_pred = model(X_teste)
after_train = criterion(y_pred, y_teste) 
print('Teste - perda depois do treinamento' , after_train.item())    


Teste - perda antes do treinamento 219.494873046875
Epoch 0: perda treino: 222.99696350097656
Epoch 1: perda treino: 222.568115234375
Epoch 2: perda treino: 222.12937927246094
Epoch 3: perda treino: 221.6784210205078
Epoch 4: perda treino: 221.21725463867188
Epoch 5: perda treino: 220.73965454101562
Epoch 6: perda treino: 220.2469940185547
Epoch 7: perda treino: 219.7390899658203
Epoch 8: perda treino: 219.21258544921875
Epoch 9: perda treino: 218.67332458496094
Epoch 10: perda treino: 218.1186065673828
Epoch 11: perda treino: 217.5505828857422
Epoch 12: perda treino: 216.96844482421875
Epoch 13: perda treino: 216.3680877685547
Epoch 14: perda treino: 215.74798583984375
Epoch 15: perda treino: 215.10577392578125
Epoch 16: perda treino: 214.43728637695312
Epoch 17: perda treino: 213.73886108398438
Epoch 18: perda treino: 213.0084228515625
Epoch 19: perda treino: 212.24267578125
Epoch 20: perda treino: 211.4459991455078
Epoch 21: perda treino: 210.6256103515625
Epoch 22: perda treino: 20